<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="3" hostname="BDC6-LX-723061Y" name="com.hasbro.sanity.SanitySuite5_WorkFlow" tests="4" failures="1" timestamp="28 Aug 2018 11:38:32 GMT" time="530.240" errors="0">
  <testcase name="tcSCFunctional" time="5.836" classname="com.hasbro.sanity.SanitySuite5_WorkFlow">
    <skipped/>
  </testcase> <!-- tcSCFunctional -->
  <testcase name="tcSCFunctional" time="1.641" classname="com.hasbro.sanity.SanitySuite5_WorkFlow">
    <skipped/>
  </testcase> <!-- tcSCFunctional -->
  <testcase name="tcSCFunctional" time="518.738" classname="com.hasbro.sanity.SanitySuite5_WorkFlow">
    <failure type="java.lang.AssertionError" message="expected [Request Sent] but found [Draft]">
      <![CDATA[java.lang.AssertionError: expected [Request Sent] but found [Draft]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at org.testng.asserts.Assertion$11.doAssert(Assertion.java:201)
at org.testng.asserts.Assertion.executeAssert(Assertion.java:30)
at org.testng.asserts.Assertion.doAssert(Assertion.java:15)
at org.testng.asserts.Assertion.assertEquals(Assertion.java:198)
at util.CommonFunctions.AssertEqualsVerification(CommonFunctions.java:257)
at com.hasbro.sanity.WorkFlowPreRequisite.SubmitRequestStatusCheck(WorkFlowPreRequisite.java:1348)
at com.hasbro.sanity.WorkFlowPreRequisite.workFlow_PreRequisite_ForTwoRetailItems(WorkFlowPreRequisite.java:145)
at com.hasbro.sanity.SanitySuite5_WorkFlow.tcSCFunctional(SanitySuite5_WorkFlow.java:160)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- tcSCFunctional -->
  <testcase name="tcSCFunctional" time="4.025" classname="com.hasbro.sanity.SanitySuite5_WorkFlow">
    <skipped/>
  </testcase> <!-- tcSCFunctional -->
</testsuite> <!-- com.hasbro.sanity.SanitySuite5_WorkFlow -->
